topik_question_task:
  description: |-
    # User Input will be preprocessed by the topik_preprocessing_task to ensure it is well-formed and standardized.

    # Guidelines
    1. Analyze the user's request and create a unique, high-quality TOPIK question based on the specified level, type, subtype, and topic.
    2. Strictly follow the principles of validity, authenticity, clarity, and plausible distractors.
    3. Ensure the question is unique for each request, even for repeated topics.
    4. Output only a single, well-formed XML document, strictly following the schema and rules below.

    # [XML STRUCTURE DEFINITION]

    - <topic_question>: (Root element)
      + <metadata>: (Required, 1)
        * <level>: (Required, 1) Difficulty level (초급, 중급, 고급).
        * <type>: (Required, 1) Main category (어휘, 문법, 읽기).
        * <subtype>: (Required, 1) Specific sub-type (e.g., 빈칸 채우기, 중심 생각 찾기).
        * <topic>: (Required, 1) The specific topic for the question content.
        * <skill>: (Required, 1) The specific language skill being tested.
      + <passage>: (Optional, 1) Enclose in <![CDATA[...]]>.
      + <question>: (Required, 1) Enclose in <![CDATA[...]]>.
      + <choices>: (Required, 1)
        * <choice id="[number]">: (Required, 4) Enclose in <![CDATA[...]]>.
      + <answer>: (Required, 1)
        * <id>: (Required, 1) The ID of the correct choice.
        * <explanation>:
          - <rationale>: (Required, 1) Enclose in <![CDATA[...]]>.
          - <distractor_analysis>:
            - <item choice_id="[number]">: (Required, 3) Enclose in <![CDATA[...]]>.

  expected_output: |-
    You MUST output only a single, well-formed XML document, strictly following this structure:
    <?xml version="1.0" encoding="UTF-8" ?>
    <topic_question>
      <metadata>
        <level>...</level>
        <type>...</type>
        <subtype>...</subtype>
        <topic>...</topic>
        <skill>...</skill>
      </metadata>
      <passage><![CDATA[...]]></passage>
      <question><![CDATA[...]]></question>
      <choices>
        <choice id="1"><![CDATA[...]]></choice>
        <choice id="2"><![CDATA[...]]></choice>
        <choice id="3"><![CDATA[...]]></choice>
        <choice id="4"><![CDATA[...]]></choice>
      </choices>
      <answer>
        <id>...</id>
        <explanation>
          <rationale><![CDATA[...]]></rationale>
          <distractor_analysis>
            <item choice_id="..."><![CDATA[...]]></item>
            <item choice_id="..."><![CDATA[...]]></item>
            <item choice_id="..."><![CDATA[...]]></item>
          </distractor_analysis>
        </explanation>
      </answer>
    </topic_question>
    All content must be inside tags, and all tags must be correctly nested and closed. Do not add any explanations or text outside the XML.
    Ensure the XML is well-formed, with no extra text or comments. Validate against the provided schema.

topik_preprocessing_task:
  description: |-
    # User Input
    - Level: {level}
    - Type: {type}
    - Subtype: {subtype}
    - Topic: {topic}

    # Guidelines
    1. Validate and normalize the user input for TOPIK question generation.
    2. Ensure the level, type, subtype, and topic are well-formed, standardized, and appropriate for TOPIK.
    3. The 'topic' field must be a detailed, well-formed description in Korean, elaborating on the topic's context, scope, or relevant aspects (not just a label). Use official TOPIK topics as a base, but expand with additional details to clarify the intended focus.
    4. The 'subtype' field must be a valid, official TOPIK subtype in Korean. If the input is not standard, correct it to the closest official subtype in Korean.
    5. If any field is missing or ambiguous, infer or suggest a suitable value based on context, always using the official TOPIK terminology in Korean.
    6. Output a single, well-formed JSON object with the following fields: level, type, subtype, topic. All values must be in Korean and standardized.
    7. Do not generate any explanations or text outside the JSON.

  expected_output: |-
    Concise information about the TOPIK question request, formatted as a single, well-formed JSON object:
    {
      "level": "...",
      "type": "...",
      "subtype": "...",
      "topic": "..."
    }
    Ensure all values are in Korean and standardized according to official TOPIK terminology. 
    The 'topic' value must be a detailed, context-rich description in Korean. 
    Do not include any explanations or text outside the JSON.